### ISSUE TITLE
Release 1.0 and publish to code.dlang.org

### ISSUE THREAD

**Issue by saurabhdas** [jamesmahler/djvm#11]
The djvm project is wonderful and potentially very very useful. I would love to see it on code.dlang.org as a dub package.

Is there any plan for releasing a 1.0 version and adding it to code.dlang.org?

**Comment by jamesmahler** [comment]
Yes at some point.  It's working well enough for projects I'm using it
with.  There are a few things I have mostly implemented that I haven't
pushed yet (like equality checking using the java objects equals and
monitor locking come to mind).

I've had a second kid though and my free time has gone to less than zero.
Whenever time frees up more, I'll finish up and push what I have out.
